local RoomTextPolicyConfig = {}

-- Compact, game-specific policy for public room navigator text.
-- Keep this list editable and modest; do not vendor external profanity datasets.
RoomTextPolicyConfig.BlockedTerms = {
	Profanity = {
		"fuck",
		"fuk",
		"shit",
		"sht",
		"bitch",
		"asshole",
		"bastard",
		"dick",
		"cunt",
		"damn",
		"crap",
	},
	Sexual = {
		"sex",
		"porn",
		"nude",
		"nsfw",
		"slut",
		"whore",
		"hookup",
		"adult only",
		"send pics",
		"make love",
	},
	Dating = {
		"dating",
		"dating room",
		"date me",
		"boyfriend",
		"girlfriend",
		"single only",
		"looking for love",
		"need bf",
		"need gf",
		"want bf",
		"want gf",
		"bf only",
		"gf only",
		"romance room",
		"kiss me",
	},
	ChildSafety = {
		"kids only",
		"children only",
		"teens only",
		"under 13",
		"under 18",
		"how old",
		"what age",
		"age check",
	},
	OffPlatformContact = {
		"discord",
		"snapchat",
		"whatsapp",
		"telegram",
		"instagram",
		"add me on",
		"dm me",
		"contact me",
		"phone number",
		"text me",
		"call me",
	},
	Scam = {
		"scam",
		"hack",
		"exploit",
		"free robux",
		"robux",
		"robux giveaway",
		"free giveaway",
		"password",
		"login",
		"phish",
	},
	HateOrSlur = {
		"hateword",
		"slur",
	},
}

RoomTextPolicyConfig.ContextTerms = {
	MinorAudience = {
		"girls only",
		"boys only",
		"kids",
		"children",
		"teens",
		"minors",
		"under 13",
		"under 18",
	},
	RomanceOrSexual = {
		"dating",
		"date me",
		"boyfriend",
		"girlfriend",
		"single only",
		"love",
		"looking for love",
		"make love",
		"romance",
		"kiss",
		"hookup",
		"adult only",
		"private love",
		"send pics",
	},
	PrivateContact = {
		"private",
		"private chat",
		"secret",
		"secret meet",
		"meet private",
		"dm me",
	},
	ScamSignal = {
		"free",
		"giveaway",
		"robux",
		"password",
		"login",
		"account",
	},
}

RoomTextPolicyConfig.CombinationRules = {
	{
		Name = "MinorRomanceContext",
		Category = "ChildSafety",
		AllContexts = { "MinorAudience", "RomanceOrSexual" },
	},
	{
		Name = "PrivateRomanceContext",
		Category = "ChildSafety",
		AllContexts = { "PrivateContact", "RomanceOrSexual" },
	},
	{
		Name = "PrivateMinorContext",
		Category = "ChildSafety",
		AllContexts = { "PrivateContact", "MinorAudience" },
	},
	{
		Name = "ScamRobuxContext",
		Category = "Scam",
		AllContexts = { "ScamSignal" },
		AnyTerms = { "robux", "password", "login" },
	},
}

RoomTextPolicyConfig.LeetReplacements = {
	["0"] = "o",
	["1"] = "i",
	["3"] = "e",
	["4"] = "a",
	["5"] = "s",
	["7"] = "t",
	["@"] = "a",
	["$"] = "s",
	["!"] = "i",
}

return RoomTextPolicyConfig
